questions = Question.create!([
                               { description: '¿Cuál es el planeta más cercano al sol?', difficulty: :easy },
                               { description: '¿Qué país es conocido por la Torre Eiffel?', difficulty: :easy },
                               { description: '¿Cuál es el océano más grande del mundo?', difficulty: :easy },
                               { description: '¿Quién pintó la Mona Lisa?', difficulty: :easy },
                               { description: '¿En qué continente se encuentra Brasil?', difficulty: :easy },
                               { description: '¿Qué instrumento musical tiene teclas blancas y negras?', difficulty: :easy },
                               { description: '¿Qué animal es conocido como el rey de la selva?', difficulty: :easy },
                               { description: '¿Qué gas es esencial para que respiremos?', difficulty: :easy },
                               { description: '¿Cuál es el nombre del río más largo del mundo?', difficulty: :easy },
                               { description: '¿En qué país se encuentra la Gran Muralla China?', difficulty: :easy },
                               { description: '¿Cuál es el animal terrestre más rápido del mundo?', difficulty: :easy },
                               { description: '¿Qué metal es conocido por su símbolo químico Fe?', difficulty: :easy },
                               { description: '¿Qué planeta es conocido como el planeta rojo?', difficulty: :easy },
                               { description: '¿Cuál es el nombre del país más grande del mundo?', difficulty: :easy },
                               { description: '¿Qué elemento químico tiene el símbolo O?', difficulty: :easy },
                               { description: '¿Qué país es famoso por el sushi?', difficulty: :easy },
                               { description: '¿Qué instrumento tiene cuerdas y se toca con un arco?', difficulty: :easy },
                               { description: '¿Qué animal produce la miel?', difficulty: :easy },
                               { description: '¿Qué deporte se juega en Wimbledon?', difficulty: :easy },
                               { description: '¿Qué animal es conocido por su capacidad de cambiar de color?', difficulty: :easy },
                               { description: '¿Qué país es conocido por sus canguros?', difficulty: :easy },
                               { description: '¿Qué se celebra el 25 de diciembre?', difficulty: :easy },
                               { description: '¿Qué fruta es conocida por su alto contenido de vitamina C?', difficulty: :easy },
                               { description: '¿Cuál es el nombre del satélite natural de la Tierra?', difficulty: :easy },
                               { description: '¿Qué animal es famoso por tener una trompa larga?', difficulty: :easy },
                               { description: '¿Cuál es la capital de Italia?', difficulty: :easy },
                               { description: '¿Qué país es conocido por el tango?', difficulty: :easy },
                               { description: '¿Qué tipo de animal es un delfín?', difficulty: :easy },
                               { description: '¿En qué ciudad se encuentra la Estatua de la Libertad?', difficulty: :easy },
                               { description: '¿Qué país tiene una hoja de arce en su bandera?', difficulty: :easy },
                               { description: '¿En qué año llegó el hombre a la luna?', difficulty: :medium },
                               { description: '¿Qué escritor escribió "Cien años de soledad"?', difficulty: :medium },
                               { description: '¿Cuál es el país más poblado del mundo?', difficulty: :medium },
                               { description: '¿Qué invento es atribuido a Alexander Graham Bell?', difficulty: :medium },
                               { description: '¿Cuál es el país más pequeño del mundo?', difficulty: :medium },
                               { description: '¿Qué fenómeno natural es medido por la escala de Richter?', difficulty: :medium },
                               { description: '¿En qué país se encuentra Machu Picchu?', difficulty: :medium },
                               { description: '¿Qué gas es el más abundante en la atmósfera terrestre?', difficulty: :medium },
                               { description: '¿Cuál es la lengua oficial de Brasil?', difficulty: :medium },
                               { description: '¿Qué órgano del cuerpo humano consume más energía?', difficulty: :medium },
                               { description: '¿Qué país ganó la Copa Mundial de Fútbol en 2018?', difficulty: :medium },
                               { description: '¿Qué científico formuló la teoría de la relatividad?', difficulty: :medium },
                               { description: '¿Qué escritor es conocido por crear a Sherlock Holmes?', difficulty: :medium },
                               { description: '¿En qué ciudad se encuentra el Kremlin?', difficulty: :medium },
                               { description: '¿Cuál es el símbolo químico del oro?', difficulty: :medium },
                               { description: '¿Qué país es famoso por el carnaval de Río de Janeiro?', difficulty: :medium },
                               { description: '¿Qué país es conocido como la tierra del sol naciente?', difficulty: :medium },
                               { description: '¿Qué océano bordea la costa este de Estados Unidos?', difficulty: :medium },
                               { description: '¿Qué famoso barco se hundió en su viaje inaugural en 1912?', difficulty: :medium },
                               { description: '¿Cuál es el único mamífero capaz de volar?', difficulty: :medium },
                               { description: '¿Qué artista pintó "La noche estrellada"?', difficulty: :medium },
                               { description: '¿En qué país se encuentra la torre inclinada de Pisa?', difficulty: :medium },
                               { description: '¿Qué país es conocido por la ópera de Sídney?', difficulty: :medium },
                               { description: '¿Qué continente es conocido por tener la mayor selva tropical?', difficulty: :medium },
                               { description: '¿En qué país se originaron los Juegos Olímpicos?', difficulty: :medium },
                               { description: '¿Qué animal es conocido por ser el más grande del océano?', difficulty: :medium },
                               { description: '¿En qué país se celebró la primera Copa Mundial de Fútbol?', difficulty: :medium },
                               { description: '¿Qué poeta escribió "El cuervo"?', difficulty: :medium },
                               { description: '¿En qué año comenzó la Segunda Guerra Mundial?', difficulty: :medium },
                               { description: '¿Qué famoso científico nació el 14 de marzo de 1879?', difficulty: :medium },
                               { description: '¿Quién escribió "La divina comedia"?', difficulty: :hard },
                               { description: '¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?', difficulty: :hard },
                               { description: '¿Cuál es la capital de Mongolia?', difficulty: :hard },
                               { description: '¿Qué químico es conocido como el padre de la tabla periódica?', difficulty: :hard },
                               { description: '¿Qué matemático es conocido por su famoso teorema sobre los triángulos rectángulos?', difficulty: :hard },
                               { description: '¿Cuál es el río más largo de Europa?', difficulty: :hard },
                               { description: '¿En qué ciudad se encuentra el Museo del Prado?', difficulty: :hard },
                               { description: '¿Qué país tiene la mayor cantidad de pirámides antiguas?', difficulty: :hard },
                               { description: '¿Qué novela comienza con "Llamadme Ismael"?', difficulty: :hard },
                               { description: '¿Cuál es el país más grande de África?', difficulty: :hard },
                               { description: '¿Qué emperador romano dividió el imperio en dos partes?', difficulty: :hard },
                               { description: '¿Qué científico descubrió la penicilina?', difficulty: :hard },
                               { description: '¿Cuál es el desierto más grande del mundo?', difficulty: :hard },
                               { description: '¿Qué autor escribió "Crimen y castigo"?', difficulty: :hard },
                               { description: '¿Cuál es la capital de Islandia?', difficulty: :hard },
                               { description: '¿Qué filósofo griego fue maestro de Alejandro Magno?', difficulty: :hard },
                               { description: '¿Qué lengua es la más hablada en el mundo?', difficulty: :hard },
                               { description: '¿Qué isla es conocida como la isla de los canguros?', difficulty: :hard },
                               { description: '¿Qué presidente de EE.UU. firmó la Proclamación de Emancipación?', difficulty: :hard },
                               { description: '¿Qué ciudad es conocida como la capital del Renacimiento?', difficulty: :hard },
                               { description: '¿Qué país se independizó de España en 1898?', difficulty: :hard },
                               { description: '¿Qué rey inglés tuvo seis esposas?', difficulty: :hard },
                               { description: '¿Cuál es el nombre de la teoría que explica el origen del universo?', difficulty: :hard },
                               { description: '¿Qué autor escribió "Don Quijote de la Mancha"?', difficulty: :hard },
                               { description: '¿Cuál es la capital de Corea del Norte?', difficulty: :hard },
                               { description: '¿Qué planeta tiene un día más largo que su año?', difficulty: :hard },
                               { description: '¿Qué artista pintó "Guernica"?', difficulty: :hard },
                               { description: '¿En qué ciudad se encuentra la Sagrada Familia?', difficulty: :hard },
                               { description: '¿Qué científico propuso las leyes del movimiento?', difficulty: :hard },
                               { description: '¿Cuál es el país más poblado de África?', difficulty: :hard }
                             ])

answers = Answer.create!([
                           { description: 'Mercurio', question: questions[0], is_correct: true },
                           { description: 'Venus', question: questions[0], is_correct: false },
                           { description: 'Tierra', question: questions[0], is_correct: false },
                           { description: 'Marte', question: questions[0], is_correct: false },

                           { description: 'Francia', question: questions[1], is_correct: true },
                           { description: 'Italia', question: questions[1], is_correct: false },
                           { description: 'Alemania', question: questions[1], is_correct: false },
                           { description: 'España', question: questions[1], is_correct: false },

                           { description: 'Océano Pacífico', question: questions[2], is_correct: true },
                           { description: 'Océano Atlántico', question: questions[2], is_correct: false },
                           { description: 'Océano Índico', question: questions[2], is_correct: false },
                           { description: 'Océano Ártico', question: questions[2], is_correct: false },

                           { description: 'Leonardo da Vinci', question: questions[3], is_correct: true },
                           { description: 'Pablo Picasso', question: questions[3], is_correct: false },
                           { description: 'Vincent van Gogh', question: questions[3], is_correct: false },
                           { description: 'Claude Monet', question: questions[3], is_correct: false },

                           { description: 'América del Sur', question: questions[4], is_correct: true },
                           { description: 'América del Norte', question: questions[4], is_correct: false },
                           { description: 'África', question: questions[4], is_correct: false },
                           { description: 'Asia', question: questions[4], is_correct: false },

                           { description: 'Piano', question: questions[5], is_correct: true },
                           { description: 'Guitarra', question: questions[5], is_correct: false },
                           { description: 'Violín', question: questions[5], is_correct: false },
                           { description: 'Flauta', question: questions[5], is_correct: false },

                           { description: 'León', question: questions[6], is_correct: true },
                           { description: 'Tigre', question: questions[6], is_correct: false },
                           { description: 'Elefante', question: questions[6], is_correct: false },
                           { description: 'Guepardo', question: questions[6], is_correct: false },

                           { description: 'Oxígeno', question: questions[7], is_correct: true },
                           { description: 'Nitrógeno', question: questions[7], is_correct: false },
                           { description: 'Dióxido de carbono', question: questions[7], is_correct: false },
                           { description: 'Hidrógeno', question: questions[7], is_correct: false },

                           { description: 'Amazonas', question: questions[8], is_correct: true },
                           { description: 'Nilo', question: questions[8], is_correct: false },
                           { description: 'Yangtsé', question: questions[8], is_correct: false },
                           { description: 'Misisipi', question: questions[8], is_correct: false },

                           { description: 'China', question: questions[9], is_correct: true },
                           { description: 'Japón', question: questions[9], is_correct: false },
                           { description: 'Corea del Sur', question: questions[9], is_correct: false },
                           { description: 'Vietnam', question: questions[9], is_correct: false },

                           { description: 'Guepardo', question: questions[10], is_correct: true },
                           { description: 'León', question: questions[10], is_correct: false },
                           { description: 'Tigre', question: questions[10], is_correct: false },
                           { description: 'Elefante', question: questions[10], is_correct: false },

                           { description: 'Hierro', question: questions[11], is_correct: true },
                           { description: 'Oro', question: questions[11], is_correct: false },
                           { description: 'Plata', question: questions[11], is_correct: false },
                           { description: 'Cobre', question: questions[11], is_correct: false },

                           { description: 'Marte', question: questions[12], is_correct: true },
                           { description: 'Venus', question: questions[12], is_correct: false },
                           { description: 'Júpiter', question: questions[12], is_correct: false },
                           { description: 'Saturno', question: questions[12], is_correct: false },

                           { description: 'Rusia', question: questions[13], is_correct: true },
                           { description: 'Canadá', question: questions[13], is_correct: false },
                           { description: 'China', question: questions[13], is_correct: false },
                           { description: 'Estados Unidos', question: questions[13], is_correct: false },

                           { description: 'Oxígeno', question: questions[14], is_correct: true },
                           { description: 'Hidrógeno', question: questions[14], is_correct: false },
                           { description: 'Helio', question: questions[14], is_correct: false },
                           { description: 'Carbono', question: questions[14], is_correct: false },

                           { description: 'Japón', question: questions[15], is_correct: true },
                           { description: 'China', question: questions[15], is_correct: false },
                           { description: 'Corea del Sur', question: questions[15], is_correct: false },
                           { description: 'Tailandia', question: questions[15], is_correct: false },

                           { description: 'Violín', question: questions[16], is_correct: true },
                           { description: 'Piano', question: questions[16], is_correct: false },
                           { description: 'Guitarra', question: questions[16], is_correct: false },
                           { description: 'Arpa', question: questions[16], is_correct: false },

                           { description: 'Abeja', question: questions[17], is_correct: true },
                           { description: 'Avispa', question: questions[17], is_correct: false },
                           { description: 'Hormiga', question: questions[17], is_correct: false },
                           { description: 'Mariposa', question: questions[17], is_correct: false },

                           { description: 'Tenis', question: questions[18], is_correct: true },
                           { description: 'Fútbol', question: questions[18], is_correct: false },
                           { description: 'Rugby', question: questions[18], is_correct: false },
                           { description: 'Béisbol', question: questions[18], is_correct: false },

                           { description: 'Camaleón', question: questions[19], is_correct: true },
                           { description: 'Serpiente', question: questions[19], is_correct: false },
                           { description: 'Rana', question: questions[19], is_correct: false },
                           { description: 'Lagarto', question: questions[19], is_correct: false },

                           { description: 'Australia', question: questions[20], is_correct: true },
                           { description: 'India', question: questions[20], is_correct: false },
                           { description: 'Sudáfrica', question: questions[20], is_correct: false },
                           { description: 'Argentina', question: questions[20], is_correct: false },

                           { description: 'Navidad', question: questions[21], is_correct: true },
                           { description: 'Año Nuevo', question: questions[21], is_correct: false },
                           { description: 'Halloween', question: questions[21], is_correct: false },
                           { description: 'Pascua', question: questions[21], is_correct: false },

                           { description: 'Naranja', question: questions[22], is_correct: true },
                           { description: 'Manzana', question: questions[22], is_correct: false },
                           { description: 'Plátano', question: questions[22], is_correct: false },
                           { description: 'Uva', question: questions[22], is_correct: false },

                           { description: 'La Luna', question: questions[23], is_correct: true },
                           { description: 'Marte', question: questions[23], is_correct: false },
                           { description: 'Venus', question: questions[23], is_correct: false },
                           { description: 'Saturno', question: questions[23], is_correct: false },

                           { description: 'Elefante', question: questions[24], is_correct: true },
                           { description: 'Jirafa', question: questions[24], is_correct: false },
                           { description: 'Rinoceronte', question: questions[24], is_correct: false },
                           { description: 'Hipopótamo', question: questions[24], is_correct: false },

                           { description: 'Roma', question: questions[25], is_correct: true },
                           { description: 'París', question: questions[25], is_correct: false },
                           { description: 'Madrid', question: questions[25], is_correct: false },
                           { description: 'Berlín', question: questions[25], is_correct: false },

                           { description: 'Argentina', question: questions[26], is_correct: true },
                           { description: 'Brasil', question: questions[26], is_correct: false },
                           { description: 'Uruguay', question: questions[26], is_correct: false },
                           { description: 'Chile', question: questions[26], is_correct: false },

                           { description: 'Mamífero', question: questions[27], is_correct: true },
                           { description: 'Reptil', question: questions[27], is_correct: false },
                           { description: 'Ave', question: questions[27], is_correct: false },
                           { description: 'Pez', question: questions[27], is_correct: false },

                           { description: 'Nueva York', question: questions[28], is_correct: true },
                           { description: 'Los Ángeles', question: questions[28], is_correct: false },
                           { description: 'Chicago', question: questions[28], is_correct: false },
                           { description: 'Miami', question: questions[28], is_correct: false },

                           { description: 'Canadá', question: questions[29], is_correct: true },
                           { description: 'Estados Unidos', question: questions[29], is_correct: false },
                           { description: 'México', question: questions[29], is_correct: false },
                           { description: 'Reino Unido', question: questions[29], is_correct: false },
                           { description: '1969', question: questions[30], is_correct: true },
                           { description: '1959', question: questions[30], is_correct: false },
                           { description: '1979', question: questions[30], is_correct: false },
                           { description: '1989', question: questions[30], is_correct: false },

                           { description: 'Gabriel García Márquez', question: questions[31], is_correct: true },
                           { description: 'Mario Vargas Llosa', question: questions[31], is_correct: false },
                           { description: 'Julio Cortázar', question: questions[31], is_correct: false },
                           { description: 'Carlos Fuentes', question: questions[31], is_correct: false },

                           { description: 'China', question: questions[32], is_correct: true },
                           { description: 'India', question: questions[32], is_correct: false },
                           { description: 'Estados Unidos', question: questions[32], is_correct: false },
                           { description: 'Indonesia', question: questions[32], is_correct: false },

                           { description: 'Teléfono', question: questions[33], is_correct: true },
                           { description: 'Radio', question: questions[33], is_correct: false },
                           { description: 'Televisión', question: questions[33], is_correct: false },
                           { description: 'Cámara', question: questions[33], is_correct: false },

                           { description: 'Ciudad del Vaticano', question: questions[34], is_correct: true },
                           { description: 'Mónaco', question: questions[34], is_correct: false },
                           { description: 'San Marino', question: questions[34], is_correct: false },
                           { description: 'Liechtenstein', question: questions[34], is_correct: false },

                           { description: 'Terremoto', question: questions[35], is_correct: true },
                           { description: 'Huracán', question: questions[35], is_correct: false },
                           { description: 'Tornado', question: questions[35], is_correct: false },
                           { description: 'Erupción volcánica', question: questions[35], is_correct: false },

                           { description: 'Perú', question: questions[36], is_correct: true },
                           { description: 'Chile', question: questions[36], is_correct: false },
                           { description: 'Bolivia', question: questions[36], is_correct: false },
                           { description: 'Ecuador', question: questions[36], is_correct: false },

                           { description: 'Nitrógeno', question: questions[37], is_correct: true },
                           { description: 'Oxígeno', question: questions[37], is_correct: false },
                           { description: 'Dióxido de carbono', question: questions[37], is_correct: false },
                           { description: 'Argón', question: questions[37], is_correct: false },

                           { description: 'Portugués', question: questions[38], is_correct: true },
                           { description: 'Español', question: questions[38], is_correct: false },
                           { description: 'Francés', question: questions[38], is_correct: false },
                           { description: 'Inglés', question: questions[38], is_correct: false },

                           { description: 'Cerebro', question: questions[39], is_correct: true },
                           { description: 'Corazón', question: questions[39], is_correct: false },
                           { description: 'Hígado', question: questions[39], is_correct: false },
                           { description: 'Pulmones', question: questions[39], is_correct: false },

                           { description: 'Francia', question: questions[40], is_correct: true },
                           { description: 'Brasil', question: questions[40], is_correct: false },
                           { description: 'Alemania', question: questions[40], is_correct: false },
                           { description: 'Argentina', question: questions[40], is_correct: false },

                           { description: 'Albert Einstein', question: questions[41], is_correct: true },
                           { description: 'Isaac Newton', question: questions[41], is_correct: false },
                           { description: 'Galileo Galilei', question: questions[41], is_correct: false },
                           { description: 'Stephen Hawking', question: questions[41], is_correct: false },

                           { description: 'Arthur Conan Doyle', question: questions[42], is_correct: true },
                           { description: 'Agatha Christie', question: questions[42], is_correct: false },
                           { description: 'Edgar Allan Poe', question: questions[42], is_correct: false },
                           { description: 'Raymond Chandler', question: questions[42], is_correct: false },

                           { description: 'Moscú', question: questions[43], is_correct: true },
                           { description: 'San Petersburgo', question: questions[43], is_correct: false },
                           { description: 'Varsovia', question: questions[43], is_correct: false },
                           { description: 'Praga', question: questions[43], is_correct: false },

                           { description: 'Au', question: questions[44], is_correct: true },
                           { description: 'Ag', question: questions[44], is_correct: false },
                           { description: 'Cu', question: questions[44], is_correct: false },
                           { description: 'Fe', question: questions[44], is_correct: false },

                           { description: 'Brasil', question: questions[45], is_correct: true },
                           { description: 'España', question: questions[45], is_correct: false },
                           { description: 'México', question: questions[45], is_correct: false },
                           { description: 'Argentina', question: questions[45], is_correct: false },

                           { description: 'Japón', question: questions[46], is_correct: true },
                           { description: 'China', question: questions[46], is_correct: false },
                           { description: 'Corea del Sur', question: questions[46], is_correct: false },
                           { description: 'India', question: questions[46], is_correct: false },

                           { description: 'Atlántico', question: questions[47], is_correct: true },
                           { description: 'Pacífico', question: questions[47], is_correct: false },
                           { description: 'Índico', question: questions[47], is_correct: false },
                           { description: 'Ártico', question: questions[47], is_correct: false },

                           { description: 'Titanic', question: questions[48], is_correct: true },
                           { description: 'Lusitania', question: questions[48], is_correct: false },
                           { description: 'Britannic', question: questions[48], is_correct: false },
                           { description: 'Olympic', question: questions[48], is_correct: false },

                           { description: 'Murciélago', question: questions[49], is_correct: true },
                           { description: 'Delfín', question: questions[49], is_correct: false },
                           { description: 'Ornitorrinco', question: questions[49], is_correct: false },
                           { description: 'Canguro', question: questions[49], is_correct: false },

                           { description: 'Vincent van Gogh', question: questions[50], is_correct: true },
                           { description: 'Pablo Picasso', question: questions[50], is_correct: false },
                           { description: 'Claude Monet', question: questions[50], is_correct: false },
                           { description: 'Leonardo da Vinci', question: questions[50], is_correct: false },

                           { description: 'Londres', question: questions[51], is_correct: true },
                           { description: 'París', question: questions[51], is_correct: false },
                           { description: 'Berlín', question: questions[51], is_correct: false },
                           { description: 'Roma', question: questions[51], is_correct: false },

                           { description: 'Platón', question: questions[52], is_correct: true },
                           { description: 'Aristóteles', question: questions[52], is_correct: false },
                           { description: 'Sócrates', question: questions[52], is_correct: false },
                           { description: 'Descartes', question: questions[52], is_correct: false },

                           { description: 'Asia', question: questions[53], is_correct: true },
                           { description: 'África', question: questions[53], is_correct: false },
                           { description: 'Europa', question: questions[53], is_correct: false },
                           { description: 'América del Norte', question: questions[53], is_correct: false },

                           { description: 'Delfín', question: questions[54], is_correct: true },
                           { description: 'Tiburón', question: questions[54], is_correct: false },
                           { description: 'Orca', question: questions[54], is_correct: false },
                           { description: 'Ballena', question: questions[54], is_correct: false },

                           { description: '1867', question: questions[55], is_correct: true },
                           { description: '1767', question: questions[55], is_correct: false },
                           { description: '1967', question: questions[55], is_correct: false },
                           { description: '1868', question: questions[55], is_correct: false },

                           { description: 'Polaco', question: questions[56], is_correct: true },
                           { description: 'Checo', question: questions[56], is_correct: false },
                           { description: 'Húngaro', question: questions[56], is_correct: false },
                           { description: 'Esloveno', question: questions[56], is_correct: false },

                           { description: 'Golfo de México', question: questions[57], is_correct: true },
                           { description: 'Golfo Pérsico', question: questions[57], is_correct: false },
                           { description: 'Golfo de Bengala', question: questions[57], is_correct: false },
                           { description: 'Golfo de Tailandia', question: questions[57], is_correct: false },

                           { description: 'Oso Panda', question: questions[58], is_correct: true },
                           { description: 'Tigre', question: questions[58], is_correct: false },
                           { description: 'León', question: questions[58], is_correct: false },
                           { description: 'Elefante', question: questions[58], is_correct: false },

                           { description: 'Machu Picchu', question: questions[59], is_correct: true },
                           { description: 'Chichén Itzá', question: questions[59], is_correct: false },
                           { description: 'Teotihuacán', question: questions[59], is_correct: false },
                           { description: 'Copán', question: questions[59], is_correct: false },

                            { description: 'Dante Alighieri', question: questions[60], is_correct: true },
                            { description: 'Miguel de Cervantes', question: questions[60], is_correct: false },
                            { description: 'Homero', question: questions[60], is_correct: false },
                            { description: 'Giovanni Boccaccio', question: questions[60], is_correct: false },

                            { description: '1776', question: questions[61], is_correct: true },
                            { description: '1789', question: questions[61], is_correct: false },
                            { description: '1799', question: questions[61], is_correct: false },
                            { description: '1804', question: questions[61], is_correct: false },

                            { description: 'Ulán Bator', question: questions[62], is_correct: true },
                            { description: 'Astana', question: questions[62], is_correct: false },
                            { description: 'Kuala Lumpur', question: questions[62], is_correct: false },
                            { description: 'Bangkok', question: questions[62], is_correct: false },

                            { description: 'Dmitri Mendeléyev', question: questions[63], is_correct: true },
                            { description: 'Marie Curie', question: questions[63], is_correct: false },
                            { description: 'Louis Pasteur', question: questions[63], is_correct: false },
                            { description: 'Antoine Lavoisier', question: questions[63], is_correct: false },

                            { description: 'Pitágoras', question: questions[64], is_correct: true },
                            { description: 'Euclides', question: questions[64], is_correct: false },
                            { description: 'Arquímedes', question: questions[64], is_correct: false },
                            { description: 'Tales de Mileto', question: questions[64], is_correct: false },

                           { description: 'Volga', question: questions[65], is_correct: true },
                           { description: 'Danubio', question: questions[65], is_correct: false },
                           { description: 'Dnieper', question: questions[65], is_correct: false },
                           { description: 'Támesis', question: questions[65], is_correct: false },

                           { description: 'Madrid', question: questions[66], is_correct: true },
                           { description: 'París', question: questions[66], is_correct: false },
                           { description: 'Londres', question: questions[66], is_correct: false },
                           { description: 'Roma', question: questions[66], is_correct: false },

                           { description: 'Egipto', question: questions[67], is_correct: true },
                           { description: 'México', question: questions[67], is_correct: false },
                           { description: 'China', question: questions[67], is_correct: false },
                           { description: 'Perú', question: questions[67], is_correct: false },

                           { description: 'Moby Dick', question: questions[68], is_correct: true },
                           { description: 'Crimen y Castigo', question: questions[68], is_correct: false },
                           { description: 'Don Quijote de la Mancha', question: questions[68], is_correct: false },
                           { description: 'Anna Karenina', question: questions[68], is_correct: false },

                           { description: 'Argelia', question: questions[69], is_correct: true },
                           { description: 'Congo', question: questions[69], is_correct: false },
                           { description: 'Sudáfrica', question: questions[69], is_correct: false },
                           { description: 'Nigeria', question: questions[69], is_correct: false },

                           { description: 'Diocleciano', question: questions[70], is_correct: true },
                           { description: 'Nerón', question: questions[70], is_correct: false },
                           { description: 'César Augusto', question: questions[70], is_correct: false },
                           { description: 'Constantino', question: questions[70], is_correct: false },

                           { description: 'Alexander Fleming', question: questions[71], is_correct: true },
                           { description: 'Louis Pasteur', question: questions[71], is_correct: false },
                           { description: 'Marie Curie', question: questions[71], is_correct: false },
                           { description: 'Antonie van Leeuwenhoek', question: questions[71], is_correct: false },

                           { description: 'Sahara', question: questions[72], is_correct: true },
                           { description: 'Gobi', question: questions[72], is_correct: false },
                           { description: 'Arabia', question: questions[72], is_correct: false },
                           { description: 'Kalahari', question: questions[72], is_correct: false },

                           { description: 'Fiódor Dostoyevski', question: questions[73], is_correct: true },
                           { description: 'Nikolái Gógol', question: questions[73], is_correct: false },
                           { description: 'Iván Turguénev', question: questions[73], is_correct: false },
                           { description: 'Lev Tolstói', question: questions[73], is_correct: false },

                           { description: 'Reikiavik', question: questions[74], is_correct: true },
                           { description: 'Oslo', question: questions[74], is_correct: false },
                           { description: 'Estocolmo', question: questions[74], is_correct: false },
                           { description: 'Copenhague', question: questions[74], is_correct: false },

                           { description: 'Aristóteles', question: questions[75], is_correct: true },
                           { description: 'Platón', question: questions[75], is_correct: false },
                           { description: 'Sócrates', question: questions[75], is_correct: false },
                           { description: 'Heráclito', question: questions[75], is_correct: false },

                           { description: 'Chino mandarín', question: questions[76], is_correct: true },
                           { description: 'Inglés', question: questions[76], is_correct: false },
                           { description: 'Español', question: questions[76], is_correct: false },
                           { description: 'Hindi', question: questions[76], is_correct: false },

                           { description: 'Australia', question: questions[77], is_correct: true },
                           { description: 'Nueva Zelanda', question: questions[77], is_correct: false },
                           { description: 'Tasmania', question: questions[77], is_correct: false },
                           { description: 'Papúa Nueva Guinea', question: questions[77], is_correct: false },

                           { description: 'Abraham Lincoln', question: questions[78], is_correct: true },
                           { description: 'George Washington', question: questions[78], is_correct: false },
                           { description: 'Andrew Johnson', question: questions[78], is_correct: false },
                           { description: 'Thomas Jefferson', question: questions[78], is_correct: false },

                           { description: 'Florencia', question: questions[79], is_correct: true },
                           { description: 'Roma', question: questions[79], is_correct: false },
                           { description: 'Venecia', question: questions[79], is_correct: false },
                           { description: 'Milán', question: questions[79], is_correct: false },

                           { description: 'Cuba', question: questions[80], is_correct: true },
                           { description: 'Puerto Rico', question: questions[80], is_correct: false },
                           { description: 'Filipinas', question: questions[80], is_correct: false },
                           { description: 'Guam', question: questions[80], is_correct: false },

                           { description: 'Enrique VIII', question: questions[81], is_correct: true },
                           { description: 'Eduardo VI', question: questions[81], is_correct: false },
                           { description: 'Jaime I', question: questions[81], is_correct: false },
                           { description: 'Carlos I', question: questions[81], is_correct: false },

                           { description: 'Big Bang', question: questions[82], is_correct: true },
                           { description: 'Teoría del Universo Oscilante', question: questions[82], is_correct: false },
                           { description: 'Teoría de Cuerdas', question: questions[82], is_correct: false },
                           { description: 'Teoría del Multiverso', question: questions[82], is_correct: false },

                           { description: 'Miguel de Cervantes', question: questions[83], is_correct: true },
                           { description: 'Garcilaso de la Vega', question: questions[83], is_correct: false },
                           { description: 'Lope de Vega', question: questions[83], is_correct: false },
                           { description: 'Federico García Lorca', question: questions[83], is_correct: false },

                           { description: 'Pyongyang', question: questions[84], is_correct: true },
                           { description: 'Seúl', question: questions[84], is_correct: false },
                           { description: 'Busan', question: questions[84], is_correct: false },
                           { description: 'Incheon', question: questions[84], is_correct: false },

                           { description: 'Venus', question: questions[85], is_correct: true },
                           { description: 'Mercurio', question: questions[85], is_correct: false },
                           { description: 'Marte', question: questions[85], is_correct: false },
                           { description: 'Júpiter', question: questions[85], is_correct: false },

                           { description: 'Pablo Picasso', question: questions[86], is_correct: true },
                           { description: 'Salvador Dalí', question: questions[86], is_correct: false },
                           { description: 'Diego Rivera', question: questions[86], is_correct: false },
                           { description: 'Vincent van Gogh', question: questions[86], is_correct: false },

                           { description: 'Barcelona', question: questions[87], is_correct: true },
                           { description: 'Madrid', question: questions[87], is_correct: false },
                           { description: 'Valencia', question: questions[87], is_correct: false },
                           { description: 'Sevilla', question: questions[87], is_correct: false },

                           { description: 'Isaac Newton', question: questions[88], is_correct: true },
                           { description: 'Galileo Galilei', question: questions[88], is_correct: false },
                           { description: 'Johannes Kepler', question: questions[88], is_correct: false },
                           { description: 'Albert Einstein', question: questions[88], is_correct: false },

                           { description: 'Nigeria', question: questions[89], is_correct: true },
                           { description: 'Egipto', question: questions[89], is_correct: false },
                           { description: 'Etiopía', question: questions[89], is_correct: false },
                           { description: 'Sudáfrica', question: questions[89], is_correct: false }

                          ])





