questions = Question.create!([
                               { description: '¿En qué año comenzó la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué evento desencadenó el inicio de la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Cuál fue el nombre del plan alemán para invadir la Unión Soviética?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué país sufrió el primer ataque atómico durante la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué conferencia decidió el destino de la Alemania post-guerra?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Quién fue el primer ministro británico durante la mayor parte de la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué fue la Batalla de Stalingrado?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué países formaban parte de las Potencias del Eje?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué fue el Día D y cuándo ocurrió?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Quién fue el presidente de los Estados Unidos durante la mayor parte de la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué nombre recibió el proyecto estadounidense para desarrollar la bomba atómica?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Cuál fue el avión caza más famoso utilizado por los británicos durante la Batalla de Inglaterra?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué fue el Enigma?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué tanque fue conocido como el "Tigre" en la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Quién fue el líder de la Unión Soviética durante la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué general estadounidense fue conocido por su liderazgo en el Teatro de Operaciones del Pacífico?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Quién fue el líder de la Alemania Nazi durante la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué general alemán fue apodado el "Zorro del Desierto"?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Cuál fue la conferencia en la que se discutió la rendición incondicional de Japón?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué fue la "Gran Alianza"?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué significan las siglas "RAF" en el contexto de la Segunda Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               { description: '¿Qué fue el Holocausto?', correct_answered: 0, incorrect_answered: 0, event: 0 },
                               
                               { description: '¿En qué país comenzó la Revolución Industrial?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿En qué siglo comenzó la Revolución Industrial?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Cuál fue una de las principales industrias que lideró la Revolución Industrial?', correct_answered: 0, incorrect_answered: 0, event: 1},
                               { description: '¿Quién inventó la máquina de vapor que impulsó la Revolución Industrial?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué sistema de producción se hizo popular durante la Revolución Industrial?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué fue la Ley de Cercamientos?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué recurso natural fue fundamental para el desarrollo de la Revolución Industrial?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué transporte se desarrolló significativamente durante la Revolución Industrial?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué invento permitió la mecanización del hilado y el tejido?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué ciudad se convirtió en un importante centro industrial en Inglaterra?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué impacto tuvo la Revolución Industrial en la población urbana?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué invento revolucionó la comunicación a larga distancia?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué movimiento social surgió en respuesta a las condiciones laborales?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué innovador proceso permitió la producción masiva de acero?', correct_answered: 0, incorrect_answered: 0, event: 1 },
                               { description: '¿Qué invento, desarrollado por Richard Trevithick, fue crucial para el transporte terrestre?', correct_answered: 0, incorrect_answered: 0, event: 1 },

                               { description: '¿En qué año comenzó la Revolución Francesa?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué evento se considera el inicio simbólico de la Revolución Francesa?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Quién fue el rey de Francia al inicio de esta revolución?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué documento proclamó los principios de libertad e igualdad?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Cuál de las siguientes no fue una causa de la Revolución Francesa?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué grupo social formó la mayoría de la población y estuvo en la base de la Revolución Francesa?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué mujer escribió la "Declaración de los Derechos de la Mujer y la Ciudadana"?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué periodo de la Revolución Francesa se caracterizó por un régimen de terror?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Quién lideró el Comité de Salvación Pública durante el Reinado del Terror?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Cuál fue el destino de Luis XVI durante la Revolución Francesa?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué acontecimiento marcó el fin del Reinado del Terror?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué gobierno reemplazó al Directorio después de su caída?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué tratado puso fin a la Guerra de la Primera Coalición contra Francia?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué asamblea juró no separarse hasta dar una Constitución a Francia?', correct_answered: 0, incorrect_answered: 0, event: 2 },
                               { description: '¿Qué conflicto interno estalló en Francia durante la Revolución, afectando especialmente la región de Vandea?', correct_answered: 0, incorrect_answered: 0, event: 2 },

                               { description: '¿En qué año ocurrieron los ataques a las Torres Gemelas?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Qué grupo terrorista fue responsable de los ataques del 11 de septiembre?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Cuántos aviones fueron secuestrados el 11 de septiembre de 2001?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Qué avión impactó primero en las Torres Gemelas?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Qué edificio, además de las Torres Gemelas, fue impactado por un avión el 11 de septiembre?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Cuál fue el destino del cuarto avión secuestrado, United Airlines Flight 93?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Qué altura tenían aproximadamente las Torres Gemelas?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Cuántas personas aproximadamente murieron en los ataques del 11 de septiembre?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Quién era el presidente de los Estados Unidos durante los ataques del 11 de septiembre?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Cómo se llamaba el líder de Al-Qaeda que planificó los ataques del 11 de septiembre?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Qué sucedió con las Torres Gemelas después de los impactos?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Qué efecto tuvo el ataque del 11 de septiembre en la economía mundial?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Qué ley se promulgó en los Estados Unidos en respuesta a los ataques del 11 de septiembre?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿Qué organismo fue creado en los Estados Unidos tras los ataques para coordinar la seguridad nacional?', correct_answered: 0, incorrect_answered: 0, event: 3 },
                               { description: '¿En qué ciudad se encontraban las Torres Gemelas?', correct_answered: 0, incorrect_answered: 0, event: 3 },

                               { description: '¿En qué año ocurrió el alunizaje del Apollo 11?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Quién fue el primer astronauta en caminar sobre la Luna durante la misión Apollo 11?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Qué astronauta se quedó en el módulo de comando mientras los otros dos exploraban la superficie lunar?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Cómo se llamaba el módulo lunar que llevó a los astronautas a la superficie de la Luna?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Qué famosa frase pronunció Neil Armstrong al pisar la Luna?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Cuánto tiempo permanecieron los astronautas en la superficie lunar durante la misión Apollo 11?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Qué presidente de los Estados Unidos anunció el objetivo de llevar a un hombre a la Luna antes de 1970?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Cuándo despegó el Apollo 11 de la Tierra?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Cómo se llamó el cohete que llevó el Apollo 11 al espacio?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Dónde aterrizó el Apollo 11 al regresar a la Tierra?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Qué planta realizaron los astronautas del Apollo 11 al regresar a la Tierra?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Cuál fue la duración total de la misión Apollo 11?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Cuál fue el nombre del programa espacial que llevó al hombre a la Luna?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Cuál fue la principal misión científica de los astronautas del Apollo 11 en la Luna?', correct_answered: 0, incorrect_answered: 0, event: 4 },
                               { description: '¿Qué hicieron los astronautas al finalizar su misión en la Luna?', correct_answered: 0, incorrect_answered: 0, event: 4 },

                               { description: '¿En qué año comenzó la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué evento desencadenó la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué países formaban parte de la Triple Alianza?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué batalla se considera una de las más largas y sangrientas de la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Cuál fue el propósito del Tratado de Versalles?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué arma fue introducida durante la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué país se unió a la guerra en 1917, inclinando la balanza a favor de los Aliados?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué imperio colapsó al final de la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué término se usó para describir el desgaste de ambos bandos durante la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Quién fue el presidente de Estados Unidos durante la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué tratado oficializó la retirada de Rusia de la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué política de guerra submarina fue empleada por Alemania durante la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Cuál fue el nombre del avión de combate más famoso de la Primera Guerra Mundial, pilotado por el Barón Rojo?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué enfermedad pandémica se propagó durante los últimos años de la Primera Guerra Mundial?', correct_answered: 0, incorrect_answered: 0, event: 5 },
                               { description: '¿Qué país cambió de bando, pasando de la Triple Alianza a los Aliados durante la guerra?', correct_answered: 0, incorrect_answered: 0, event: 5 }
                             ])

answers = Answer.create!([
                           { description: '1938', question: questions[0], is_correct: false },
                           { description: '1939', question: questions[0], is_correct: true },
                           { description: '1940', question: questions[0], is_correct: false },
                           { description: '1941', question: questions[0], is_correct: false },

                           { description: 'El ataque a Pearl Harbor', question: questions[1], is_correct: false },
                           { description: 'La invasión de Francia', question: questions[1], is_correct: false },
                           { description: 'La invasión de Polonia', question: questions[1], is_correct: true },
                           { description: 'El bombardeo de Londres', question: questions[1], is_correct: false },

                           { description: 'Operación Overlord', question: questions[2], is_correct: false },
                           { description: 'Operación Market Garden', question: questions[2], is_correct: false },
                           { description: 'Operación Barbarroja', question: questions[2], is_correct: true },
                           { description: 'Operación Torch', question: questions[2], is_correct: false },

                           { description: 'Alemania', question: questions[3], is_correct: false },
                           { description: 'Italia', question: questions[3], is_correct: false },
                           { description: 'China', question: questions[3], is_correct: false },
                           { description: 'Japón', question: questions[3], is_correct: true },

                           { description: 'Conferencia de Teherán', question: questions[4], is_correct: false },
                           { description: 'Conferencia de Yalta', question: questions[4], is_correct: true },
                           { description: 'Conferencia de Potsdam', question: questions[4], is_correct: false },
                           { description: 'Conferencia de Múnich', question: questions[4], is_correct: false },

                           { description: 'Neville Chamberlain', question: questions[5], is_correct: false },
                           { description: 'Clement Attlee', question: questions[5], is_correct: false },
                           { description: 'Winston Churchill', question: questions[5], is_correct: true },
                           { description: 'Anthony Eden', question: questions[5], is_correct: false },

                           { description: 'Una batalla naval en el Pacífico', question: questions[6], is_correct: false },
                           { description: 'Una batalla aérea sobre Gran Bretaña', question: questions[6], is_correct: false },
                           { description: 'Una batalla en el norte de África', question: questions[6], is_correct: false },
                           { description: 'Una batalla en el Frente Oriental', question: questions[6], is_correct: true },

                           { description: 'Alemania, Francia y Japón', question: questions[7], is_correct: false },
                           { description: 'Alemania, Italia y Japón', question: questions[7], is_correct: true },
                           { description: 'Alemania, Italia y China', question: questions[7], is_correct: false },
                           { description: 'Alemania, Rusia y Japón', question: questions[7], is_correct: false },

                           { description: 'La invasión de Polonia en 1939', question: questions[8], is_correct: false },
                           { description: 'La invasión de Francia en 1940', question: questions[8], is_correct: false },
                           { description: 'La invasión de Normandía en 1944', question: questions[8], is_correct: true },
                           { description: 'La rendición de Alemania en 1945', question: questions[8], is_correct: false },

                           { description: 'Harry S. Truman', question: questions[9], is_correct: false },
                           { description: 'Dwight D. Eisenhower', question: questions[9], is_correct: false },
                           { description: 'Herbert Hoover', question: questions[9], is_correct: false },
                           { description: 'Franklin D. Roosevelt', question: questions[9], is_correct: true },

                           { description: 'Proyecto Omega', question: questions[10], is_correct: false },
                           { description: 'Proyecto Manhattan', question: questions[10], is_correct: true },
                           { description: 'Proyecto Mercury', question: questions[10], is_correct: false },
                           { description: 'Proyecto Trinity', question: questions[10], is_correct: false },

                           { description: 'P-51 Mustang', question: questions[11], is_correct: false },
                           { description: 'Focke-Wulf Fw 190', question: questions[11], is_correct: false },
                           { description: 'Supermarine Spitfire', question: questions[11], is_correct: true },
                           { description: 'Messerschmitt Bf 109', question: questions[11], is_correct: false },

                           { description: 'Un submarino alemán', question: questions[12], is_correct: false },
                           { description: 'Un tanque británico', question: questions[12], is_correct: false },
                           { description: 'Una máquina de cifrado alemana', question: questions[12], is_correct: true },
                           { description: 'Un radar estadounidense', question: questions[12], is_correct: false },

                           { description: 'Panzer IV', question: questions[13], is_correct: false },
                           { description: 'Panther', question: questions[13], is_correct: false },
                           { description: 'Panzer VI Tiger', question: questions[13], is_correct: true },
                           { description: 'Sherman', question: questions[13], is_correct: false },

                           { description: 'Leon Trotsky', question: questions[14], is_correct: false },
                           { description: 'Nikita Khrushchev', question: questions[14], is_correct: false },
                           { description: 'Iósif Stalin', question: questions[14], is_correct: true },
                           { description: 'Vladimir Lenin', question: questions[14], is_correct: false },

                           { description: 'George S. Patton', question: questions[15], is_correct: false },
                           { description: 'Dwight D. Eisenhower', question: questions[15], is_correct: false },
                           { description: 'Omar Bradley', question: questions[15], is_correct: false },
                           { description: 'Douglas MacArthur', question: questions[15], is_correct: true },

                           { description: 'Heinrich Himmler', question: questions[16], is_correct: false },
                           { description: 'Hermann Göring', question: questions[16], is_correct: false },
                           { description: 'Joseph Goebbels', question: questions[16], is_correct: false },
                           { description: 'Adolf Hitler', question: questions[16], is_correct: true },

                           { description: 'Heinz Guderian', question: questions[17], is_correct: false },
                           { description: 'Erwin Rommel', question: questions[17], is_correct: true },
                           { description: 'Gerd von Rundstedt', question: questions[17], is_correct: false },
                           { description: 'Wilhelm Keitel', question: questions[17], is_correct: false },

                           { description: 'Conferencia de Casablanca', question: questions[18], is_correct: false },
                           { description: 'Conferencia de Teherán', question: questions[18], is_correct: false },
                           { description: 'Conferencia de Potsdam', question: questions[18], is_correct: true },
                           { description: 'Conferencia de Yalta', question: questions[18], is_correct: false },

                           { description: 'La alianza entre Alemania, Italia y Japón', question: questions[19], is_correct: false },
                           { description: 'La alianza entre Estados Unidos, el Reino Unido y la Unión Soviética', question: questions[19], is_correct: true },
                           { description: 'La alianza entre Francia, Reino Unido y Polonia', question: questions[19], is_correct: false },
                           { description: 'La alianza entre Estados Unidos, China y el Reino Unido', question: questions[19], is_correct: false },

                           { description: 'Royal Army Force', question: questions[20], is_correct: false },
                           { description: 'Royal Air Force', question: questions[20], is_correct: true },
                           { description: 'Russian Armed Forces', question: questions[20], is_correct: false },
                           { description: 'Reich Air Fleet', question: questions[20], is_correct: false },

                           { description: 'El bombardeo de Londres por Alemania', question: questions[21], is_correct: false },
                           { description: 'La invasión de Francia por las fuerzas aliadas', question: questions[21], is_correct: false },
                           { description: 'El genocidio perpetrado por el régimen nazi contra los judíos y otros grupos minoritarios', question: questions[21], is_correct: true },
                           { description: 'La guerra de guerrillas en el sudeste asiático', question: questions[21], is_correct: false },

                           { description: 'Francia', question: questions[22], is_correct: false },
                           { description: 'Estados Unidos', question: questions[22], is_correct: false },
                           { description: 'Alemania', question: questions[22], is_correct: false },
                           { description: 'Reino Unido', question: questions[22], is_correct: true },

                           { description: 'Siglo XVII', question: questions[23], is_correct: false },
                           { description: 'Siglo XVIII', question: questions[23], is_correct: true },
                           { description: 'Siglo XIX', question: questions[23], is_correct: false },
                           { description: 'Siglo XX', question: questions[23], is_correct: false },

                           { description: 'La industria textil', question: questions[24], is_correct: true },
                           { description: 'La industria automotriz', question: questions[24], is_correct: false },
                           { description: 'La industria aeronáutica', question: questions[24], is_correct: false },
                           { description: 'La industria electrónica', question: questions[24], is_correct: false },

                           { description: 'Thomas Edison', question: questions[25], is_correct: false },
                           { description: 'James Watt', question: questions[25], is_correct: true },
                           { description: 'Alexander Graham Bell', question: questions[25], is_correct: false },
                           { description: 'Nikola Tesla', question: questions[25], is_correct: false },

                           { description: 'El sistema feudal', question: questions[26], is_correct: false },
                           { description: 'El sistema de talleres artesanales', question: questions[26], is_correct: false },
                           { description: 'El sistema fabril', question: questions[26], is_correct: true },
                           { description: 'El sistema de trueque', question: questions[26], is_correct: false },

                           { description: 'Una ley que prohibía el trabajo infantil', question: questions[27], is_correct: false },
                           { description: 'Una ley que permitía la privatización de tierras comunales', question: questions[27], is_correct: true },
                           { description: 'Una ley que regulaba los horarios de trabajo', question: questions[27], is_correct: false },
                           { description: 'Una ley que fomentaba la educación pública', question: questions[27], is_correct: false },

                           { description: 'El petróleo', question: questions[28], is_correct: false },
                           { description: 'El carbón', question: questions[28], is_correct: true },
                           { description: 'El gas natural', question: questions[28], is_correct: false },
                           { description: 'La madera', question: questions[28], is_correct: false },

                           { description: 'El avión', question: questions[29], is_correct: false },
                           { description: 'El automóvil', question: questions[29], is_correct: false },
                           { description: 'El tren', question: questions[29], is_correct: true },
                           { description: 'El barco de vapor', question: questions[29], is_correct: false },

                           { description: 'La máquina de vapor', question: questions[30], is_correct: false },
                           { description: 'La máquina de coser', question: questions[30], is_correct: false },
                           { description: 'La lanzadera volante', question: questions[30], is_correct: true },
                           { description: 'El telégrafo', question: questions[30], is_correct: false },

                           { description: 'Londres', question: questions[31], is_correct: false },
                           { description: 'Manchester', question: questions[31], is_correct: true },
                           { description: 'Birmingham', question: questions[31], is_correct: false },
                           { description: 'Liverpool', question: questions[31], is_correct: false },

                           { description: 'Disminuyó la población urbana', question: questions[32], is_correct: false },
                           { description: 'Aumentó la población urbana', question: questions[32], is_correct: true },
                           { description: 'No tuvo impacto en la población urbana', question: questions[32], is_correct: false },
                           { description: 'La población urbana se mantuvo estable', question: questions[32], is_correct: false },

                           { description: 'El teléfono', question: questions[33], is_correct: false },
                           { description: 'El telégrafo', question: questions[33], is_correct: true },
                           { description: 'La radio', question: questions[33], is_correct: false },
                           { description: 'La televisión', question: questions[33], is_correct: false },

                           { description: 'El movimiento feminista', question: questions[34], is_correct: false },
                           { description: 'El movimiento obrero', question: questions[34], is_correct: true },
                           { description: 'El movimiento ambientalista', question: questions[34], is_correct: false },
                           { description: 'El movimiento pacifista', question: questions[34], is_correct: false },

                           { description: 'El proceso Bessemer', question: questions[35], is_correct: true },
                           { description: 'El proceso de destilación', question: questions[35], is_correct: false },
                           { description: 'El proceso de fermentación', question: questions[35], is_correct: false },
                           { description: 'El proceso de pasteurización', question: questions[35], is_correct: false },

                           { description: 'El automóvil', question: questions[36], is_correct: false },
                           { description: 'El tractor', question: questions[36], is_correct: false },
                           { description: 'El tren a vapor', question: questions[36], is_correct: true },
                           { description: 'La bicicleta', question: questions[36], is_correct: false },

                           { description: '1787', question: questions[37], is_correct: false },
                           { description: '1789', question: questions[37], is_correct: true },
                           { description: '1791', question: questions[37], is_correct: false },
                           { description: '1793', question: questions[37], is_correct: false },

                           { description: 'La toma de la Bastilla', question: questions[38], is_correct: true },
                           { description: 'La ejecución de Luis XVI', question: questions[38], is_correct: false },
                           { description: 'La Declaración de los Derechos del Hombre y del Ciudadano', question: questions[38], is_correct: false },
                           { description: 'La marcha sobre Versalles', question: questions[38], is_correct: false },

                           { description: 'Luis XIV', question: questions[39], is_correct: false },
                           { description: 'Luis XV', question: questions[39], is_correct: false },
                           { description: 'Luis XVI', question: questions[39], is_correct: true },
                           { description: 'Carlos X', question: questions[39], is_correct: false },

                           { description: 'La Constitución de 1791', question: questions[40], is_correct: false },
                           { description: 'El Código Napoleónico', question: questions[40], is_correct: false },
                           { description: 'La Declaración de los Derechos del Hombre y del Ciudadano', question: questions[40], is_correct: true },
                           { description: 'El Tratado de Versalles', question: questions[40], is_correct: false },

                           { description: 'Desigualdad social', question: questions[41], is_correct: false },
                           { description: 'Crisis económica', question: questions[41], is_correct: false },
                           { description: 'Expansión del Imperio Francés', question: questions[41], is_correct: true },
                           { description: 'Ideas de la Ilustración', question: questions[41], is_correct: false },

                           { description: 'La nobleza', question: questions[42], is_correct: false },
                           { description: 'El clero', question: questions[42], is_correct: false },
                           { description: 'El tercer estado', question: questions[42], is_correct: true },
                           { description: 'Los militares', question: questions[42], is_correct: false },

                           { description: 'Marie Antoinette', question: questions[43], is_correct: false },
                           { description: 'Charlotte Corday', question: questions[43], is_correct: false },
                           { description: 'Olympe de Gouges', question: questions[43], is_correct: true },
                           { description: 'Jeanne Roland', question: questions[43], is_correct: false },

                           { description: 'La Asamblea Nacional', question: questions[44], is_correct: false },
                           { description: 'La Convención Nacional', question: questions[44], is_correct: true },
                           { description: 'El Directorio', question: questions[44], is_correct: false },
                           { description: 'El Consulado', question: questions[44], is_correct: false },

                           { description: 'Georges Danton', question: questions[45], is_correct: false },
                           { description: 'Jean-Paul Marat', question: questions[45], is_correct: false },
                           { description: 'Maximilien Robespierre', question: questions[45], is_correct: true },
                           { description: 'Napoleón Bonaparte', question: questions[45], is_correct: false },

                           { description: 'Fue exiliado', question: questions[46], is_correct: false },
                           { description: 'Fue asesinado', question: questions[46], is_correct: false },
                           { description: 'Fue guillotinado', question: questions[46], is_correct: true },
                           { description: 'Fue encarcelado de por vida', question: questions[46], is_correct: false },

                           { description: 'La ejecución de Robespierre', question: questions[47], is_correct: true },
                           { description: 'La proclamación de la República', question: questions[47], is_correct: false },
                           { description: 'La firma del Tratado de Campo Formio', question: questions[47], is_correct: false },
                           { description: 'La coronación de Napoleón', question: questions[47], is_correct: false },

                           { description: 'La Monarquía Constitucional', question: questions[48], is_correct: false },
                           { description: 'El Consulado', question: questions[48], is_correct: true },
                           { description: 'El Imperio', question: questions[48], is_correct: false },
                           { description: 'La Asamblea Legislativa', question: questions[48], is_correct: false },

                           { description: 'El Tratado de Amiens', question: questions[49], is_correct: false },
                           { description: 'El Tratado de Campo Formio', question: questions[49], is_correct: true },
                           { description: 'El Tratado de Versalles', question: questions[49], is_correct: false },
                           { description: 'El Tratado de París', question: questions[49], is_correct: false },

                           { description: 'La Asamblea Nacional Constituyente', question: questions[50], is_correct: true },
                           { description: 'La Convención Nacional', question: questions[50], is_correct: false },
                           { description: 'Los Estados Generales', question: questions[50], is_correct: false },
                           { description: 'La Asamblea Legislativa', question: questions[50], is_correct: false },

                           { description: 'La Guerra de los Tres Reinos', question: questions[51], is_correct: false },
                           { description: 'La Guerra Civil de Vandea', question: questions[51], is_correct: true },
                           { description: 'La Guerra de los Segadores', question: questions[51], is_correct: false },
                           { description: 'La Rebelión de los Camisardos', question: questions[51], is_correct: false },

                           { description: '1999', question: questions[52], is_correct: false },
                           { description: '2000', question: questions[52], is_correct: false },
                           { description: '2001', question: questions[52], is_correct: true },
                           { description: '2002', question: questions[52], is_correct: false },

                           { description: 'Al-Qaeda', question: questions[53], is_correct: true },
                           { description: 'ISIS', question: questions[53], is_correct: false },
                           { description: 'Boko Haram', question: questions[53], is_correct: false },
                           { description: 'Hezbollah', question: questions[53], is_correct: false },

                           { description: '2', question: questions[54], is_correct: false },
                           { description: '3', question: questions[54], is_correct: false },
                           { description: '4', question: questions[54], is_correct: true },
                           { description: '5', question: questions[54], is_correct: false },

                           { description: 'American Airlines Flight 11', question: questions[55], is_correct: true },
                           { description: 'United Airlines Flight 93', question: questions[55], is_correct: false },
                           { description: 'American Airlines Flight 77', question: questions[55], is_correct: false },
                           { description: 'United Airlines Flight 175', question: questions[55], is_correct: false },

                           { description: 'El Capitolio', question: questions[56], is_correct: false },
                           { description: 'La Casa Blanca', question: questions[56], is_correct: false },
                           { description: 'El Pentágono', question: questions[56], is_correct: true },
                           { description: 'La Torre Sears', question: questions[56], is_correct: false },

                           { description: 'Impactó en el Pentágono', question: questions[57], is_correct: false },
                           { description: 'Fue derribado por cazas estadounidenses', question: questions[57], is_correct: false },
                           { description: 'Se estrelló en un campo en Pensilvania', question: questions[57], is_correct: true },
                           { description: 'Impactó en la Casa Blanca', question: questions[57], is_correct: false },

                           { description: '300 metros', question: questions[58], is_correct: false },
                           { description: '400 metros', question: questions[58], is_correct: true },
                           { description: '450 metros', question: questions[58], is_correct: false },
                           { description: '500 metros', question: questions[58], is_correct: false },

                           { description: '1500', question: questions[59], is_correct: false },
                           { description: '2000', question: questions[59], is_correct: false },
                           { description: '2500', question: questions[59], is_correct: false },
                           { description: '3000', question: questions[59], is_correct: true },

                           { description: 'Bill Clinton', question: questions[60], is_correct: false },
                           { description: 'George W. Bush', question: questions[60], is_correct: true },
                           { description: 'Barack Obama', question: questions[60], is_correct: false },
                           { description: 'Donald Trump', question: questions[60], is_correct: false },

                           { description: 'Abu Bakr al-Baghdadi', question: questions[61], is_correct: false },
                           { description: 'Osama bin Laden', question: questions[61], is_correct: true },
                           { description: 'Ayman al-Zawahiri', question: questions[61], is_correct: false },
                           { description: 'Khalid Sheikh Mohammed', question: questions[61], is_correct: false },

                           { description: 'Fueron parcialmente destruidas', question: questions[62], is_correct: false },
                           { description: 'Se incendiaron pero permanecieron en pie', question: questions[62], is_correct: false },
                           { description: 'Se derrumbaron completamente', question: questions[62], is_correct: true },
                           { description: 'Sólo una de las torres se derrumbó', question: questions[62], is_correct: false },

                           { description: 'No tuvo efecto significativo', question: questions[63], is_correct: false },
                           { description: 'Provocó una recesión global', question: questions[63], is_correct: true },
                           { description: 'Fortaleció la economía global', question: questions[63], is_correct: false },
                           { description: 'Aceleró el crecimiento económico', question: questions[63], is_correct: false },

                           { description: 'Patriot Act', question: questions[64], is_correct: true },
                           { description: 'Homeland Security Act', question: questions[64], is_correct: false },
                           { description: 'USA Freedom Act', question: questions[64], is_correct: false },
                           { description: 'National Defense Authorization Act', question: questions[64], is_correct: false },

                           { description: 'CIA', question: questions[65], is_correct: false },
                           { description: 'FBI', question: questions[65], is_correct: false },
                           { description: 'Department of Homeland Security', question: questions[65], is_correct: true },
                           { description: 'National Security Agency', question: questions[65], is_correct: false },

                           { description: 'Washington D.C.', question: questions[66], is_correct: false },
                           { description: 'Boston', question: questions[66], is_correct: false },
                           { description: 'Nueva York', question: questions[66], is_correct: true },
                           { description: 'Chicago', question: questions[66], is_correct: false },

                           { description: '1967', question: questions[67], is_correct: false },
                           { description: '1968', question: questions[67], is_correct: false },
                           { description: '1969', question: questions[67], is_correct: true },
                           { description: '1970', question: questions[67], is_correct: false },

                           { description: 'Michael Collins', question: questions[68], is_correct: false },
                           { description: 'Buzz Aldrin', question: questions[68], is_correct: false },
                           { description: 'Neil Armstrong', question: questions[68], is_correct: true },
                           { description: 'John Glenn', question: questions[68], is_correct: false },

                           { description: 'Michael Collins', question: questions[69], is_correct: true },
                           { description: 'Buzz Aldrin', question: questions[69], is_correct: false },
                           { description: 'Neil Armstrong', question: questions[69], is_correct: false },
                           { description: 'Alan Shepard', question: questions[69], is_correct: false },

                           { description: 'Columbia', question: questions[70], is_correct: false },
                           { description: 'Eagle', question: questions[70], is_correct: true },
                           { description: 'Endeavour', question: questions[70], is_correct: false },
                           { description: 'Challenger', question: questions[70], is_correct: false },

                           { description: 'Es un pequeño paso para un hombre, un gran salto para la humanidad.', question: questions[71], is_correct: true },
                           { description: 'La águila ha aterrizado.', question: questions[71], is_correct: false },
                           { description: 'Aquí hay un trozo de la Luna.', question: questions[71], is_correct: false },
                           { description: 'Estamos en la Luna.', question: questions[71], is_correct: false },

                           { description: 'Menos de 12 horas', question: questions[72], is_correct: false },
                           { description: 'Aproximadamente 24 horas', question: questions[72], is_correct: true },
                           { description: 'Aproximadamente 36 horas', question: questions[72], is_correct: false },
                           { description: 'Más de 48 horas', question: questions[72], is_correct: false },

                           { description: 'Dwight D. Eisenhower', question: questions[73], is_correct: false },
                           { description: 'John F. Kennedy', question: questions[73], is_correct: true },
                           { description: 'Lyndon B. Johnson', question: questions[73], is_correct: false },
                           { description: 'Richard Nixon', question: questions[73], is_correct: false },

                           { description: '16 de julio', question: questions[74], is_correct: true },
                           { description: '20 de julio', question: questions[74], is_correct: false },
                           { description: '24 de julio', question: questions[74], is_correct: false },
                           { description: '26 de julio', question: questions[74], is_correct: false },

                           { description: 'Saturn I', question: questions[75], is_correct: false },
                           { description: 'Saturn IB', question: questions[75], is_correct: false },
                           { description: 'Saturn V', question: questions[75], is_correct: true },
                           { description: 'Saturn VII', question: questions[75], is_correct: false },

                           { description: 'Océano Atlántico', question: questions[76], is_correct: false },
                           { description: 'Océano Índico', question: questions[76], is_correct: false },
                           { description: 'Océano Pacífico', question: questions[76], is_correct: true },
                           { description: 'Golfo de México', question: questions[76], is_correct: false },

                           { description: 'Visitaron el Capitolio', question: questions[77], is_correct: false },
                           { description: 'Una gira mundial', question: questions[77], is_correct: true },
                           { description: 'Un desfile en Nueva York', question: questions[77], is_correct: false },
                           { description: 'Un encuentro con el Papa', question: questions[77], is_correct: false },

                           { description: '11 días', question: questions[78], is_correct: false },
                           { description: '8 días', question: questions[78], is_correct: true },
                           { description: '13 días', question: questions[78], is_correct: false },
                           { description: '15 días', question: questions[78], is_correct: false },

                           { description: 'Programa Mercury', question: questions[79], is_correct: false },
                           { description: 'Programa Apollo', question: questions[79], is_correct: true },
                           { description: 'Programa Moon', question: questions[79], is_correct: false },
                           { description: 'Programa Skylap', question: questions[79], is_correct: false },

                           { description: 'Construir una base lunar', question: questions[80], is_correct: false },
                           { description: 'Instalar instrumentos científicos y recoger muestras de suelo lunar', question: questions[80], is_correct: true },
                           { description: 'Fotografiar la superficie lunar', question: questions[80], is_correct: false },
                           { description: 'Realizar experimentos de gravedad', question: questions[80], is_correct: false },

                           { description: 'Regresaron al módulo de comando y volvieron a la Tierra', question: questions[81], is_correct: false },
                           { description: 'Permanecieron en órbita lunar por un tiempo', question: questions[81], is_correct: true },
                           { description: 'Establecieron comunicación con la Tierra', question: questions[81], is_correct: false },
                           { description: 'Tomaron más fotografías de la superficie lunar', question: questions[81], is_correct: false },

                           { description: '1912', question: questions[82], is_correct: false },
                           { description: '1914', question: questions[82], is_correct: true },
                           { description: '1916', question: questions[82], is_correct: false },
                           { description: '1918', question: questions[82], is_correct: false },

                           { description: 'El hundimiento del Lusitania', question: questions[83], is_correct: false },
                           { description: 'El asesinato del archiduque Francisco Fernando', question: questions[83], is_correct: true },
                           { description: 'La invasión de Polonia', question: questions[83], is_correct: false },
                           { description: 'La firma del Tratado de Versalles', question: questions[83], is_correct: false },

                           { description: 'Alemania, Austria-Hungría e Italia', question: questions[84], is_correct: true },
                           { description: 'Francia, Rusia y Reino Unido', question: questions[84], is_correct: false },
                           { description: 'Estados Unidos, Francia y Rusia', question: questions[84], is_correct: false },
                           { description: 'Alemania, Rusia y Japón', question: questions[84], is_correct: false },

                           { description: 'La Batalla del Somme', question: questions[85], is_correct: false },
                           { description: 'La Batalla de Verdún', question: questions[85], is_correct: true },
                           { description: 'La Batalla de Gallipoli', question: questions[85], is_correct: false },
                           { description: 'La Batalla de Ypres', question: questions[85], is_correct: false },

                           { description: 'Establecer la Liga de las Naciones', question: questions[86], is_correct: false },
                           { description: 'Culminar la guerra y sancionar a Alemania', question: questions[86], is_correct: true },
                           { description: 'Acordar el desarme de todas las naciones', question: questions[86], is_correct: false },
                           { description: 'Repartir las colonias alemanas entre los Aliados', question: questions[86], is_correct: false },

                           { description: 'Tanques', question: questions[87], is_correct: true },
                           { description: 'Arcos largos', question: questions[87], is_correct: false },
                           { description: 'Submarinos nucleares', question: questions[87], is_correct: false },
                           { description: 'Bombas atómicas', question: questions[87], is_correct: false },

                           { description: 'Japón', question: questions[88], is_correct: false },
                           { description: 'Estados Unidos', question: questions[88], is_correct: true },
                           { description: 'China', question: questions[88], is_correct: false },
                           { description: 'España', question: questions[88], is_correct: false },

                           { description: 'El Imperio Otomano', question: questions[89], is_correct: true },
                           { description: 'El Imperio Chino', question: questions[89], is_correct: false },
                           { description: 'El Imperio Británico', question: questions[89], is_correct: false },
                           { description: 'El Imperio Persa', question: questions[89], is_correct: false },

                           { description: 'Guerra relámpago', question: questions[90], is_correct: false },
                           { description: 'Guerra de desgaste', question: questions[90], is_correct: true },
                           { description: 'Guerra de movimientos', question: questions[90], is_correct: false },
                           { description: 'Guerra asimétrica', question: questions[90], is_correct: false },

                           { description: 'Franklin D. Roosevelt', question: questions[91], is_correct: false },
                           { description: 'Woodrow Wilson', question: questions[91], is_correct: true },
                           { description: 'Herbert Hoover', question: questions[91], is_correct: false },
                           { description: 'Harry S. Truman', question: questions[91], is_correct: false },

                           { description: 'El Tratado de Trianon', question: questions[92], is_correct: false },
                           { description: 'El Tratado de Brest-Litovsk', question: questions[92], is_correct: true },
                           { description: 'El Tratado de Saint-Germain', question: questions[92], is_correct: false },
                           { description: 'El Tratado de Neuilly', question: questions[92], is_correct: false },

                           { description: 'Submarinos en aguas restringidas', question: questions[93], is_correct: false },
                           { description: 'Guerra submarina irrestricta', question: questions[93], is_correct: true },
                           { description: 'Submarinos en patrulla costera', question: questions[93], is_correct: false },
                           { description: 'Guerra submarina defensiva', question: questions[93], is_correct: false },

                           { description: 'Fokker Dr.I', question: questions[94], is_correct: true },
                           { description: 'Sopwith Camel', question: questions[94], is_correct: false },
                           { description: 'Spad S.XIII', question: questions[94], is_correct: false },
                           { description: 'Albatros D.III', question: questions[94], is_correct: false },

                           { description: 'La gripe española', question: questions[95], is_correct: true },
                           { description: 'La peste bubónica', question: questions[95], is_correct: false },
                           { description: 'El cólera', question: questions[95], is_correct: false },
                           { description: 'La viruela', question: questions[95], is_correct: false },

                           { description: 'Italia', question: questions[96], is_correct: true },
                           { description: 'Japón', question: questions[96], is_correct: false },
                           { description: 'Bulgaria', question: questions[96], is_correct: false },
                           { description: 'Rumania', question: questions[96], is_correct: false }
                         ])